version: "2"

services:
  web:
    build: ./
    image: wikisual_web
    volumes:
      - .:/opt/wikisual
    working_dir: /opt/wikisual
    hostname: wookie-web
    command: /usr/local/bin/python ./manage.py runserver 0.0.0.0:8080
    ports:
      - "8080:8080"
    depends_on:
      - postgres.local
      - redis.local

  rcstream:
    image: wikisual_web
    volumes:
      - .:/opt/wikisual
    working_dir: /opt/wikisual
    hostname: wookie-web
    command: /usr/local/bin/python ./manage.py rcstream
    depends_on:
      - postgres.local

  push-to-group:
    image: wikisual_web
    volumes:
      - .:/opt/wikisual
    working_dir: /opt/wikisual
    hostname: wookie-web
    command: /usr/local/bin/python ./manage.py push-to-group
    depends_on:
      - postgres.local
      - redis.local

  postgres.local:
    image: postgres:9.6
    ports:
      - "5432:5432"

  redis.local:
    image: redis
