# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-13 05:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wikicollector', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recentchange',
            name='type',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
    ]
