# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-25 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wikicollector', '0002_recentchange_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recentchange',
            name='timestamp',
            field=models.DateTimeField(db_index=True),
        ),
    ]
